### ISSUE TITLE
tests on Jenkins

### ISSUE THREAD

**Issue by aleeciu** [CLIMADA-project/climada_python#143]
According to Jenkins, test_blackmarble.py is only crashing at Test2013.test_sint_maarten, but when I run the file in spyder with the develop branch I get way more errors, basically all tests within that file are crashing...

what am I missing? is Jenkins only running on main? I thought it was running on develop too...

**Comment by ThomasRoosli** [comment]
For me all 15 tests in test_black_marble.py passed and returned ok. Does this relate to test files and the new CONFIG? maybe the solution in this issue helps you as well: #132 
(as a sidenote, on jenkins I only see one blackmarble test failing and it is climada.entity.exposures.test.test_black_marble.TestNightLight.test_cut_country_brb_2km_pass, seen on: https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/develop/350/)

**Comment by aleeciu** [comment]
Hi thomas, I am referring to the integration _test_blackmarble.py_, not to the unit test _test_black_marble.py_; for which all 15 tests run fine for me too. Could you maybe try that too? (it takes a while, though, unless you already have downloaded the data)

Or maybe just try one of tests in the file, but a different one than Test2013.test_sint_maarten, which is the only which should actually crash according to https://ied-wcr-jenkins.ethz.ch/job/climada_ci_night/lastCompletedBuild/testReport/

**Comment by emanuel-schmid** [comment]
The jenkins project climada_ci_night has the same environment as climada_branches. It's configured in the requirements/env_climada.yml file of the develop branch.

I have run blackmarble integration tests locally on windows with basically the same outcome as jenkins.

Can you post a typical error message from the 15 failed tests?

**Comment by ThomasRoosli** [comment]
I have been running two tests of the `climada.test.test_blackmarble.py` file on windows. I can report the same problem as described by @aleeciu, all tests failed. The Error was always: `FileNotFoundError: [Errno 2] No such file or directory: 'C:\\shortpaths\\GitHub\\climada_python\\climada\\test\\results\\F182013.v4.tar'`. It occured somewhere here: `File "C:\shortpaths\GitHub\climada_python\climada\entity\exposures\nightlight.py", line 382, in load_nightlight_noaa`.
To me it seems that `SYSTEMS_DIR` in `climada.entity.exposures.nightlight.py` is somehow wrongly assigned. I hope this helps for finding the error. I will not have time to further look into that in the following days.

**Comment by aleeciu** [comment]
Yes it has to do with how the SYSTEM_DIR path is managed, as well as where the NOAA files are saved, I guess these errors are due to the latest configs changes. Anyway, I have now fixed them and will create a pull request tomorrow.

The only remaining issue to me is why Jenkins did not capture them...

**Comment by tovogt** [comment]
One test in `test_black_marble` is still failing on Jenkins, even though it's not failing locally for me: https://ied-wcr-jenkins.ethz.ch/job/climada_branches/job/develop/359/testReport/junit/climada.entity.exposures.test.test_black_marble/TestNightLight/test_cut_country_brb_2km_pass/

**Comment by aleeciu** [comment]
Yes that has always been failing on jenkins but never locally .... (see first comment from Thomas to this thread which was prior to #146 )

**Comment by emanuel-schmid** [comment]
the still failing test `test_cut_country_brb_2km_pass` is caused by scipy update to 1.6 (see pull request #174)
